apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xhbci0b7r-go 
  janus-idp.io/tekton: xhbci0b7r-go
  backstage.io/kubernetes-id: xhbci0b7r-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xhbci0b7r-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml